// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios; // Use iOS config for macOS as fallback
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return web; // Use web config for linux as fallback
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNQTWcCbuM_Ns4EJCkSIe0mFn9h5Ya2dU',
    appId: '1:422544642479:web:9da27d3cad255f94e4df5a',
    messagingSenderId: '422544642479',
    projectId: 'smartexpenseapp-4e111',
    authDomain: 'smartexpenseapp-4e111.firebaseapp.com',
    storageBucket: 'smartexpenseapp-4e111.firebasestorage.app',
    measurementId: 'G-PHQFRE2NSN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMYqOQW6G_3IR1Awt5HE-WENyXyN6xNlA',
    appId: '1:422544642479:android:80cf63b589f8fab0e4df5a',
    messagingSenderId: '422544642479',
    projectId: 'smartexpenseapp-4e111',
    storageBucket: 'smartexpenseapp-4e111.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6xiNTSZsDD8Q-XAIqrdD8WSckf_bCgsc',
    appId: '1:422544642479:ios:9546151b97b8a6aee4df5a',
    messagingSenderId: '422544642479',
    projectId: 'smartexpenseapp-4e111',
    storageBucket: 'smartexpenseapp-4e111.firebasestorage.app',
    iosBundleId: 'com.smartexpense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6xiNTSZsDD8Q-XAIqrdD8WSckf_bCgsc',
    appId: '1:422544642479:ios:9546151b97b8a6aee4df5a',
    messagingSenderId: '422544642479',
    projectId: 'smartexpenseapp-4e111',
    storageBucket: 'smartexpenseapp-4e111.firebasestorage.app',
    iosBundleId: 'com.smartexpense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNQTWcCbuM_Ns4EJCkSIe0mFn9h5Ya2dU',
    appId: '1:422544642479:web:1b077a567f5bfe01e4df5a',
    messagingSenderId: '422544642479',
    projectId: 'smartexpenseapp-4e111',
    authDomain: 'smartexpenseapp-4e111.firebaseapp.com',
    storageBucket: 'smartexpenseapp-4e111.firebasestorage.app',
    measurementId: 'G-7QP059ET6G',
  );

}